### ISSUE TITLE
Départ de Sentier logo

### ISSUE THREAD

**Issue by cmutel** [Depart-de-Sentier/Prizes#5]
# Summary

As a large and important international NGO (yeah right), we need a logo. It should be inspired by, but to closely linked, to the [Brightway logo](https://github.com/brightway-lca/logo). Wikipedia has [some information](https://fr.wikipedia.org/wiki/D%C3%A9part_de_sentier) on the meaning of our name.

Keywords for inspiration:

* Citizen science
* Hiking paths
* Sustainability

See also [the legal purposes of our association](https://github.com/Depart-de-Sentier/Legal/blob/main/Statutes/statutes_en.md#2-purpose)

# Prize Amount

100 € or CHF

# Output

* A logo, developed in iteration (within this issue) with @cmutel and other DdS staff, and provided in both vector and raster (multiple sizes) formats, including both black & white and colored versions, provided as a PR to this repository.
* Logo color scheme as a graphic and text file with hex and RGB codes.

# Verification

Verification will be done by @cmutel, who will provide feedback during the iterative design process.

**Comment by cmutel** [comment]
Task done externally.

**Comment by proov** [comment]
Hello !

first attempt : 
![Plan de travail 3](https://user-images.githubusercontent.com/1095527/168488988-5349735a-f521-4c11-b126-ad583f3a3872.png)

edit: some explanations: It's a topographic map, it can reminds the wood too. I cropped the pattern to something balanced. If you look closely you can see the D and the S (initials) in the lines, at first i wanted to show this a bit more with dotted lines, but it was a bit too much in my opinion. I prefer to keep the logo simple. The shades of greens represents the forest and the nature of course, and to accentuate the technical and scientific skills, i chose darker and a bit desaturated greens. It creates a more technical and professional look. I also added a baseline because your name is a little unconventional. We can modify it or remove it if you think it's unecessary.
a word on the typography, i wanted a rounded typeface (but not too much) for the warm and human side, the larger x-height gives an open readability even in small sizes, in full caps it brings some stability. 
Hope you will like it ;)

quick exemple in use on a web page : 
<img width="2035" alt="Capture d’écran 2022-05-15 à 20 21 06" src="https://user-images.githubusercontent.com/1095527/168488641-d006bb48-cbe2-40ff-a7b7-ff2f266e9535.png">

**Comment by tngTUDOR** [comment]
@proov thank you very much for your design, we at DdS really like it !

- [x] We should remove the "OPEN SUSTAINABILITY" from the logo. Only keep the topographic map + "DÉPART DE SENTIER" because the "open sustainability" text gets lost in smaller logo implementations.
- [x] We prefer the logo version where we can see the frame around the topographic map
- [x] Even if brightway and DdS are not equivalent, do you think you could propose versions of the DdS logo where the [colors from brightway](https://github.com/brightway-lca/logo/blob/main/1_Design_information/Design_information.pdf) can be used to make a coherent set?

**Comment by proov** [comment]
Sure, The logo with the frame was inrtented to use with light backgrounds. BUt maybe i can keep the frame on dark backgrounds too, i'll try :p
Ok for the Brightway colors, btw the palette is "cooler", u will lose a bit of warm.

**Comment by proov** [comment]
With Brightway colors :
- dark on white
- light blue on dark
- small dark on white
- small blue on dark with bright green
![v2](https://user-images.githubusercontent.com/1095527/169909420-92607b1c-eb7e-4e99-82b1-9bfabc6c0bc8.png)

I dont recommend this bright green on light backgrounds (or with a white text above, eg. button) due to the low contrast.

Quick example on a web page with a darker button
<img width="2018" alt="Capture d’écran 2022-05-23 à 23 30 28" src="https://user-images.githubusercontent.com/1095527/169909457-b99145a2-2b50-4cd1-9ca3-52c9775a9d7f.png">

**Comment by tngTUDOR** [comment]
Thank you very much @proov .
We prefer the first set of colors, with the second design. Can you please prepare a final version providing the design information, source files and so on ?
See the [brightway logo repo](https://github.com/brightway-lca/logo) to get an idea of what we expects as "design information" (and of course, you can improve the design information if you have others things that we must also put in there).

**Comment by proov** [comment]
Hello ! yes i prefer the 1st set of colors too. Of course I'll give you the source and the guidelines asap ;)

Note: the Urbane Rounded Font is a commercial font, if you want to use it on a website (for big titles), the licence is 39€. Or if you have a Adobe Creative Cloud account, it's included inside ;)

**Comment by cmutel** [comment]
https://github.com/Depart-de-Sentier/dds-logo
